# Generated by Django 4.2.1 on 2023-07-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=65)),
                ('verified', models.BooleanField()),
                ('active', models.BooleanField()),
                ('tier', models.PositiveSmallIntegerField()),
                ('files_transferred_mb', models.PositiveIntegerField()),
                ('api_calls_count', models.PositiveIntegerField()),
                ('last_api_call_month', models.DateField(auto_now=True)),
            ],
        ),
    ]
